import './globals.css';
import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import { Inter } from 'next/font/google';
import { ClientCookiesProvider } from './provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={inter.className}>
      <ClientCookiesProvider value={cookies().getAll()}>
        {children}
      </ClientCookiesProvider>
    </body>
  </html>
);

// eslint-disable-next-line import/no-default-export
export default RootLayout;
