import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { CookiesProvider } from 'next-client-cookies/server';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={inter.className}>
      <CookiesProvider>{children}</CookiesProvider>
    </body>
  </html>
);

// eslint-disable-next-line import/no-default-export
export default RootLayout;
